FROM node:18 AS builder
WORKDIR /build
COPY package.json package-lock.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src/ ./src/
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:18
COPY --from=builder /build/dist/ ${LAMBDA_TASK_ROOT}/dist/
COPY package.json package-lock.json ${LAMBDA_TASK_ROOT}/
RUN npm ci --omit=dev
CMD ["dist/handler.handler"]
